### ISSUE TITLE
Hi,I'd like to ask you some questions about how to test the model trained by your capsule net code?

### ISSUE THREAD

**Issue by chenshuo0012** [thibo73800/capsnet_traffic_sign_classifier#1]
I test the model trained by your capsule net code followed your guide as:
$> python test.py outputs/checkpoints/ckpt_name dataset/ 
but the terminal point out the error:
Traceback (most recent call last):
  File "test.py", line 100, in <module>
    test(arguments["<dataset>"], arguments["<ckpt>"])
  File "test.py", line 81, in test
    model.load(ckpt)
  File "/home/cs/capsnet_traffic_sign_classifier/model_base.py", line 317, in load
    tensors = json.loads(tensors)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Could you tell me how to  test the model?

**Comment by thibo73800** [comment]
Hi, 

"outputs/checkpoints/ckpt_name dataset/" is only an example of what you are supposed to do once your model is trained. 
To test the model, you first need to train one.
