### ISSUE TITLE
How to make own .p pickle?

### ISSUE THREAD

**Issue by chikiuso** [thibo73800/capsnet_traffic_sign_classifier#12]
Anyone knows how to make own dataset (.p pickle) for this project? thanks.

**Comment by vsraghavhk** [comment]
I would like to know the answer to this too, please. 

I tried pickling the dataset folders as such, but the pickle files from the repo stores numpy arrays of the images. Not sure how to handle classes here(?)

Would be very helpful if someone could explain the structure of the data pickled here, as well.

**Comment by thibo73800** [comment]
I used the pickle module 
https://wiki.python.org/moin/UsingPickle
