### ISSUE TITLE
ValueError: unsupported pickle protocol: 4

### ISSUE THREAD

**Issue by jhasuman** [thibo73800/capsnet_traffic_sign_classifier#2]
Hi, I was trying to run train.py dataset on AWS cloud with ubuntu 14.04 but got this error, I am pasting all the errors, please help me help me on how to fix this ? 

ValueErrorTraceback (most recent call last)
/home/ubuntu/capsnet-traffic-sign-classifier/train.py in <module>()
    123 if __name__ == '__main__':
    124     arguments = docopt(__doc__)
--> 125     train(arguments["<dataset>"], arguments["--ckpt"], arguments["<output>"])

/home/ubuntu/capsnet-traffic-sign-classifier/train.py in train(dataset, ckpt, output)
     53         return np.array(img) / 255
     54 
---> 55     X_train, y_train, X_valid, y_valid, X_test, y_test = get_data(dataset)
     56 
     57     X_train = X_train / 255

/home/ubuntu/capsnet-traffic-sign-classifier/data_handler.pyc in get_data(folder)
     21 
     22     with open(training_file, mode='rb') as f:
---> 23         train = pickle.load(f)
     24     with open(validation_file, mode='rb') as f:
     25         valid = pickle.load(f)

/usr/lib/python2.7/pickle.pyc in load(file)
   1376 
   1377 def load(file):
-> 1378     return Unpickler(file).load()
   1379 
   1380 def loads(str):

/usr/lib/python2.7/pickle.pyc in load(self)
    856             while 1:
    857                 key = read(1)
--> 858                 dispatch[key](self)
    859         except _Stop, stopinst:
    860             return stopinst.value

/usr/lib/python2.7/pickle.pyc in load_proto(self)
    884         proto = ord(self.read(1))
    885         if not 0 <= proto <= 2:
--> 886             raise ValueError, "unsupported pickle protocol: %d" % proto
    887     dispatch[PROTO] = load_proto
    888 

ValueError: unsupported pickle protocol: 4

**Comment by thibo73800** [comment]
I forgot to precise it in the README.  I will add it.
You need python3.

**Comment by thibo73800** [comment]
I just push to up the test accuracy to 96,97%

**Comment by thibo73800** [comment]
97% now

**Comment by jhasuman** [comment]
WooW!! That's Amazing!! I am hoping you are going to increase it further.
