### ISSUE TITLE
can't read dataset

### ISSUE THREAD

**Issue by Thanhpqt92** [thibo73800/capsnet_traffic_sign_classifier#4]
File "train.py", line 125, in <module>
    train(arguments["<dataset>"], arguments["--ckpt"], arguments["<output>"])
  File "train.py", line 55, in train
    X_train, y_train, X_valid, y_valid, X_test, y_test = get_data(dataset)
  File "/home/unist/Documents/CapsNet/capsnet-traffic-sign-classifier/data_handler.py", line 23, in get_data
    train = pickle.load(f)
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

I have this problem. I am using python3.
Please help me to solve this problem or any comments about this one.
Thank you a lot

**Comment by thibo73800** [comment]
Hi, what is your os?

**Comment by Thanhpqt92** [comment]
Thank you for your attention,
I'm using Ubuntu14.04

**Comment by thibo73800** [comment]
I can't reproduce your issue.

Maybe you can try to add encoding='utf8' in each 'open' method in the file data_handler.py and/or adding this line at the beginning: 

import sys
sys.setdefaultencoding('utf-8') 

Let me know if you keep stuck

**Comment by Thanhpqt92** [comment]
Thank you a lot for your attention.

I found a way to fix it, add one more option to data_handle

    with open(training_file,'rb') as f:
        train = pickle.load(f)
    with open(validation_file,'rb') as f:
        valid = pickle.load(f)
    with open(testing_file, 'rb') as f:
        test = pickle.load(f)

Once, thank you.
Best wishes,

**Comment by Thanhpqt92** [comment]
Thank you a lot for your attention.

I found a way to fix it, I've removed the "model" in reading part of data_handle

with open(training_file,'rb') as f:
    train = pickle.load(f)
with open(validation_file,'rb') as f:
    valid = pickle.load(f)
with open(testing_file, 'rb') as f:
    test = pickle.load(f)

Once, thank you.
Best wishes,
