### ISSUE TITLE
How to draw the loss and accuracy diagrams with tensorboard?

### ISSUE THREAD

**Issue by amirhfarzaneh** [thibo73800/capsnet_traffic_sign_classifier#8]
How do you use tensorboard to draw the loss and accuracy diagrams in the end?

Also how do you set an specific number of epochs for the algorithm to stop?

**Comment by thibo73800** [comment]
Do you mean how to visualize the loss and accuracy?

To set a number of epochs, you need to edit the file train.py by replacing the "while True" line by something like this: "for e in range(epoch)"
